CREATE TABLE car_entity (
  id INTEGER NOT NULL,
   make VARCHAR(255),
   model VARCHAR(255),
   color VARCHAR(255),
   release_year INTEGER NOT NULL,
   price_per_hour DOUBLE PRECISION NOT NULL,
   CONSTRAINT pk_carentity PRIMARY KEY (id)
);


CREATE TABLE customer_entity (
  id INTEGER NOT NULL,
   address VARCHAR(255),
   email VARCHAR(255),
   CONSTRAINT pk_customerentity PRIMARY KEY (id)
);

CREATE TABLE booking_entity (
  id INTEGER NOT NULL,
   start_time TIMESTAMP WITHOUT TIME ZONE,
   end_time TIMESTAMP WITHOUT TIME ZONE,
   state VARCHAR(255),
   booking_car INTEGER,
   booking_customer INTEGER,
   CONSTRAINT pk_bookingentity PRIMARY KEY (id)
);

ALTER TABLE booking_entity ADD CONSTRAINT FK_BOOKINGENTITY_ON_BOOKING_CAR FOREIGN KEY (booking_car) REFERENCES car_entity (id);

ALTER TABLE booking_entity ADD CONSTRAINT FK_BOOKINGENTITY_ON_BOOKING_CUSTOMER FOREIGN KEY (booking_customer) REFERENCES customer_entity (id);

CREATE TABLE user_info (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   email VARCHAR(255),
   password VARCHAR(255),
   roles VARCHAR(255),
   CONSTRAINT pk_userinfo PRIMARY KEY (id)
);
